volumes:
  tmp_data:

services:
  hw_sim_alice:
    build:
      context: .
      dockerfile: Dockerfile.simulator
    command: simulator --config-path /data/hw_sim_config.json
    network_mode: "host"
    volumes:
      - ./config_files/alice:/data
      - tmp_data:/tmp

  hw_sim_bob:
    build:
      context: .
      dockerfile: Dockerfile.simulator
    command: simulator --config-path /data/hw_sim_config.json
    network_mode: "host"
    volumes:
      - ./config_files/bob:/data
      - tmp_data:/tmp

  gc_alice:
    build:
      context: .
      dockerfile: Dockerfile.simulator
    command: gc_alice -c /data/gc_config.json
    network_mode: "host"
    volumes:
      - ./config_files/alice:/data
      - tmp_data:/tmp
    depends_on:
      - hw_sim_alice

  gc_bob:
    build:
      context: .
      dockerfile: Dockerfile.simulator
    command: gc_bob -c /data/gc_config.json
    network_mode: "host"
    volumes:
      - ./config_files/bob:/data
      - tmp_data:/tmp
    depends_on:
      - hw_sim_bob

  qber_bob:
    build:
      context: .
      dockerfile: Dockerfile.qber
    command: bob -c /data/qber_config.json
    network_mode: "host"
    volumes:
      - ./config_files/bob:/data
      - tmp_data:/tmp
    depends_on:
      - gc_bob

  qber_alice:
    build:
      context: .
      dockerfile: Dockerfile.qber
    command: sh -c "sleep 2 && alice -c /data/qber_config.json 6400"
    network_mode: "host"
    volumes:
      - ./config_files/alice:/data
      - tmp_data:/tmp
    depends_on:
      - gc_alice
      - qber_bob